apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name | default "parameter-store" }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.clusterSecretStore.region | quote }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.clusterSecretStore.authSecretRef.name }}
            namespace: {{ .Values.clusterSecretStore.authSecretRef.namespace }}
            key: {{ .Values.clusterSecretStore.authSecretRef.accessKeyIDKey }}
          secretAccessKeySecretRef:
            name: {{ .Values.clusterSecretStore.authSecretRef.name }}
            namespace: {{ .Values.clusterSecretStore.authSecretRef.namespace }}
            key: {{ .Values.clusterSecretStore.authSecretRef.secretAccessKeyKey }}
