{{- with .Values.clusterSecretStore }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .name | default "parameter-store" }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .region | quote }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .authSecretRef.name }}
            namespace: {{ .authSecretRef.namespace }}
            key: {{ .authSecretRef.accessKeyIDKey }}
          secretAccessKeySecretRef:
            name: {{ .authSecretRef.name }}
            namespace: {{ .authSecretRef.namespace }}
            key: {{ .authSecretRef.secretAccessKeyKey }}
{{- end }}
