apiVersion: v2
name: kube-prometheus-stack-bundle
description: kube-prometheus-stack umbrella for kkamji clusters
type: application
version: 0.1.0
appVersion: "v0.83.0"
dependencies:
  - name: kube-prometheus-stack
    version: 75.12.0
    repository: https://prometheus-community.github.io/helm-charts
